[package]
name = "find-places-db"
version = "0.1.0"
authors = ["Thom Chiovoloni <chiovolonit@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Quick and dirty crate for finding a user's local places databases"

[dependencies]
dirs = "1.0.3"
failure = "0.1.2"
log = "0.4.4"
